# Generated by Django 2.0.7 on 2018-07-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tokens',
            options={'ordering': ['token']},
        ),
    ]
