# Generated by Django 2.0.7 on 2018-07-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'ordering': ['question']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question']},
        ),
        migrations.AlterModelOptions(
            name='questionset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='quicknotes',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['syllabus']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['name']},
        ),
    ]
