# Generated by Django 2.0.7 on 2018-07-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180708_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter',
            new_name='unit',
        ),
    ]
