# Generated by Django 2.0.7 on 2018-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180712_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
