# Generated by Django 2.0.7 on 2018-07-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questionset_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.Subject'),
        ),
    ]
