# Generated by Django 2.0.7 on 2018-07-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180716_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.AlterField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.Subject'),
        ),
    ]
