# Generated by Django 2.0 on 2018-07-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180716_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
